site_name: 大气科学 | 课程资源
site_description: 浙江大学地科学院 大气科学 专业课程指南
site_author: 好想喝抹茶

nav:
  -  大气主页: index.md
  -  专业基础课程:
      - 常微分方程: basic/ode.md
      - 地球科学导论: basic/introduction_to_earth_science.md
      - 概率论与数理统计: basic/probability_and_mathematical_statistics.md
      - 数理方法（甲）1: basic/methods_of_mathematical_physics.md
  -  专业必修课程:
      - 大气探测学: required/atmospheric_observation.md
      - 现代气候学基础: required/fundamentals_of_modern_climatology.md
      - 大气物理和化学: required/atmospheric_physics_and_chemistry.md
      - 现代天气学+AI: required/modern_synoptic_meteorology_ai.md
      - 动力气象学: required/dynamic_meteorology.md
  -  专业选修课程:
      - 地理信息科学导论: elective/gis_intro.md
      - 遥感概论: elective/rs.md
      - 地学数理统计分析: elective/geological_data_statistic_analysis.md
      - 大气科学程序设计: elective/atmospheric_science_programming.md
      - 大气辐射: elective/atmospheric_radiation.md
      - 地貌学与第四纪地质: elective/geomorphology_and_quaternary_geology.md
      - 气候科学中的热门话题: elective/hot_topics_in_climate_science.md
  -  实践教学环节:
      - 大气探索: practice/atmospheric_survey.md
      - 大气科学认知实习: practice/atmospheric_probing_intern.md
      - 大气科学专业实习: practice/professional_practice4as.md
      - 大气科学综合实习: practice/comprehensive_practice_in_as.md
  -  本专业进阶模块: 
      - 统计气象学: advanced/statistical_meteorology.md
      - 全球气候与环境演变: advanced/global_climatic_and_environmental_change.md
      - 智能大气环境建模与气候风险评估: advanced/atmospheric_environment_modeling.md
      - 天气分析预报及ai应用: advanced/weather_analysis_forecasting_and_aiapplications.md
      - 数值天气预报: advanced/numerical_weather_prediction.md
      - 地球科学人工智能方法: advanced/ai_in_es.md
      - 数据挖掘与机器学习: advanced/data_mining_and_machine_learning.md



theme:
  name: material
  # logo: logo.ico  # 本地有这个文件后再取消注释
  # favicon: logo.ico
  font:
    text: Roboto  # 或者使用 Inter, Lato 等非衬线字体
    code: Roboto Mono
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    # - navigation.footer
    - navigation.tabs # 开启顶部横向导航栏（非常关键）
    - content.code.annotate
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
  language: 'zh'
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - 'from_oi_wiki/css/extra.css?v=13' # 本地有文件后再取消注释
  - css/extra.css
  # - css/neoteroi-mkdocs.css

extra_javascript:
  - 'from_oi_wiki/js/extra.js' # 本地有文件后再取消注释
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js

plugins:
  - search:
      jieba_dict: dict.txt.big # 本地有该字典文件后再取消注释
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: timeago
  # - statistics     # 需要单独安装 mkdocs-statistics-plugin
  # - termynal       # 需要单独安装 mkdocs-termynal
  # - glightbox      # 需要单独安装 mkdocs-glightbox
  # - rss            # 需要单独安装 mkdocs-rss-plugin

copyright: 'Copyright &copy; 2026 cc98-地球科学学院，保留一切权利。'